### ISSUE TITLE
Movie dao update bug / moviecontroller - update

### ISSUE THREAD

**Issue by MichalBeran** [MichalBeran/Movies-Catalogue#106]
Bug while updating movie in dao layer. Take a look o create.
If you add new genre to existing film, it won't propagate this change.

**Comment by arrynn** [comment]
zrejme tam treba delegovat tie zmeny na actor a genre service

resp najst povodny film, najst k nemu vsetky genre a actors, zmazat im ten film, najst genre a hercov z  jsonu, nastavit im ten film a zmigrovat ich updatom cez ich fasady

**Comment by MichalBeran** [comment]
solved.
