### ISSUE TITLE
Create JPA implementation of Actor DAO and Director DAO

### ISSUE THREAD

**Issue by MichalBeran** [MichalBeran/Movies-Catalogue#12]
Create JPA implementation of Actor DAO and Director DAO.

**Comment by arrynn** [comment]
commit 159f1fa9f2dd7c304d6d99d64300030b35e0a20f
Author: Marek Urban <umarekk@gmail.com>
Date:   Sat Oct 28 16:39:15 2017 +0200

    fix method return type

commit 5864f619c29553fd29cd0fddfefcca01daac6f2d
Author: Marek Urban <umarekk@gmail.com>
Date:   Sat Oct 28 16:37:11 2017 +0200

    create JPA implementation of ActorDao and DirectorDao

commit f8339f62914fb5c650fb909d71aeff553fe340ff
Author: Marek Urban <umarekk@gmail.com>
Date:   Sat Oct 28 16:35:48 2017 +0200

    change ActorDao and DirectorDao method arguments
