### ISSUE TITLE
ServiceLayer exceptions

### ISSUE THREAD

**Issue by domeniqo** [MichalBeran/Movies-Catalogue#125]
in FindById methods we don't check whether entity with given id exists and we automatically call beanMappingService to map entity to DTO,class... when we call some method of REST API which use this funkction with parameter of non-existing entity.. instead of returning badRequest, there's thrown exception and response is 500 Internal Server Error
try curl -i -X GET http://localhost:8080/pa165/rest/genres/4
or curl -i -X GET http://localhost:8080/pa165/rest/movies/4

**Comment by arrynn** [comment]
the method in genre is missing a trycatch block, that would fix this issue.
