### ISSUE TITLE
there is not enough seed data

### ISSUE THREAD

**Issue by arrynn** [MichalBeran/Movies-Catalogue#190]
* add at least 4 more movies with another genres. That also includes appropriate directors and actors. 
* Ensure there is at least one director in our seed data that has 2 or more movies. 
* Ensure there is at least one actor having 2 or more movies.

* Add more registered users and also add some reviews from each of the registered users so the movie index shows the rating values (stars) for most of the films. 
* Use real review texts to mimic a real example (and also to test the visual presentation of reviews in the movie detail).

**Comment by MichalBeran** [comment]
Solved in pull request #203.
